# Generated by Django 5.0.2 on 2024-02-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0002_assetimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='image',
        ),
    ]
