# Generated by Django 5.0.2 on 2024-02-27 14:21

import asset_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0003_remove_asset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(default=asset_management.models.generate_asset_code, editable=False, max_length=16, unique=True),
        ),
    ]
